config/routes.rb
Rails.application.routes.draw do
  root 'weather_forecasts#index'
  
  resources :weather_forecasts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather_forecast.rb
class WeatherForecast < ApplicationRecord
  def get_weather_data
    ForecastIO.forecast(lat, lng)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_forecasts_controller.rb
class WeatherForecastsController < ApplicationController
  before_action :set_weather_forecast, only: [:show, :edit, :update, :destroy]

  # GET /weather_forecasts
  # GET /weather_forecasts.json
  def index
    @weather_forecasts = WeatherForecast.all
    @weather_forecast = WeatherForecast.new
  end

  # GET /weather_forecasts/1
  # GET /weather_forecasts/1.json
  def show
    @weather = @weather_forecast.get_weather_data
    @current_conditions = @weather.currently
    @daily_weather = @weather.daily.data.first(7)

  end

  # GET /weather_forecasts/new
  def new
    @weather_forecast = WeatherForecast.new
  end

  # GET /weather_forecasts/1/edit
  def edit
  end

  # POST /weather_forecasts
  # POST /weather_forecasts.json
  def create
    @weather_forecast = WeatherForecast.new(weather_forecast_params)

    respond_to do |format|
      if @weather_forecast.save
        format.html { redirect_to @weather_forecast, notice: 'Weather forecast was successfully created.' }
        format.json { render :show, status: :created, location: @weather_forecast }
      else
        format.html { render :new }
        format.json { render json: @weather_forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weather_forecasts/1
  # PATCH/PUT /weather_forecasts/1.json
  def update
    respond_to do |format|
      if @weather_forecast.update(weather_forecast_params)
        format.html { redirect_to @weather_forecast, notice: 'Weather forecast was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather_forecast }
      else
        format.html { render :edit }
        format.json { render json: @weather_forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_forecasts/1
  # DELETE /weather_forecasts/1.json
  def destroy
    @weather_forecast.destroy
    respond_to do |format|
      format.html { redirect_to weather_forecasts_url, notice: 'Weather forecast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_forecast
      @weather_forecast = WeatherForecast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_forecast_params
      params.require(:weather_forecast).permit(:lat, :lng, :address, :lattitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_forecasts_helper.rb
module WeatherForecastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forecast</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather_forecasts/_form.html.erb
<%= form_for(weather_forecast) do |f| %>
  <% if weather_forecast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather_forecast.errors.count, "error") %> prohibited this weather_forecast from being saved:</h2>

      <ul>
      <% weather_forecast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %>
    <%= f.text_field :lat %>
  </div>

  <div class="field">
    <%= f.label :lng %>
    <%= f.text_field :lng %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weather_forecasts/edit.html.erb
<h1>Editing Weather Forecast</h1>

<%= render 'form', weather_forecast: @weather_forecast %>

<%= link_to 'Show', @weather_forecast %> |
<%= link_to 'Back', @weather_forecast %>

app/views/weather_forecasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weather Forecasts</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @weather_forecasts.each do |weather_forecast| %>
      <tr>
        <td><%= weather_forecast.lat %></td>
        <td><%= weather_forecast.lng %></td>
        <td><%= link_to 'Show', weather_forecast %></td>
        <td><%= link_to 'Edit', edit_weather_forecast_path(weather_forecast) %></td>
        <td><%= link_to 'Destroy', weather_forecast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather Forecast', new_weather_forecast_path %>

<br>
<br>

app/views/weather_forecasts/new.html.erb
<h1>New Weather Forecast</h1>

<%= render 'form', weather_forecast: @weather_forecast %>

<%= link_to 'Back', weather_forecasts_path %>

app/views/weather_forecasts/show.html.erb
<p id="notice"><%= notice %></p>

<div>
<h1>Coordinates</h1>
<strong>Latitude:<%= @weather_forecast.lat %> |
Longitude:<%= @weather_forecast.lng %> </strong>
</div>

<div>
  <h2> <%= @current_conditions.summary %> and <%= @current_conditions.temperature %> </h2>
</div>

<div>
  <% @daily_weather.each do |day| %><br>
  <%= Time.at(day.time).strftime('%A') %>
  <span> <h4> <%= day.summary %><br>
      High: <%= day.apparentTemperatureMax %> | Low: <%= day.apparentTemperatureMin %><br>
  <% end %>
  </span>
</div>

<br>
<span>
<%= link_to 'Edit', edit_weather_forecast_path(@weather_forecast) %> |
<%= link_to 'Back', weather_forecasts_path %>
</span>